window.Modernizr=function(h,e,l){function k(d,b){return typeof d===b}function A(d,b){for(var s in d){var a=d[s];if(!~(""+a).indexOf("-")&&g[a]!==l)return"pfx"==b?a:!0}return!1}function c(d,b,s){var a=d.charAt(0).toUpperCase()+d.slice(1),e=(d+" "+B.join(a+" ")+a).split(" ");if(k(b,"string")||k(b,"undefined"))return A(e,b);e=(d+" "+C.join(a+" ")+a).split(" ");a:{var d=e,f;for(f in d)if(a=b[d[f]],a!==l){if(!1===s){b=d[f];break a}b=k(a,"function")?a.bind(s||b):a;break a}b=!1}return b}function G(){f.input=
function(d){for(var b=0,a=d.length;b<a;b++)n[d[b]]=!!(d[b]in i);if(n.list)n.list=!(!e.createElement("datalist")||!h.HTMLDataListElement);return n}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));f.inputtypes=function(d){for(var b=0,a,o,f=d.length;b<f;b++){i.setAttribute("type",o=d[b]);if(a="text"!==i.type)i.value=u,i.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(o)&&i.style.WebkitAppearance!==l?(j.appendChild(i),a=e.defaultView,a=
a.getComputedStyle&&"textfield"!==a.getComputedStyle(i,null).WebkitAppearance&&0!==i.offsetHeight,j.removeChild(i)):/^(search|tel)$/.test(o)||(a=/^(url|email)$/.test(o)?i.checkValidity&&!1===i.checkValidity():i.value!=u);D[d[b]]=!!a}return D}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var f={},j=e.documentElement,a=e.createElement("modernizr"),g=a.style,i=e.createElement("input"),u=":)",E={}.toString,p=" -webkit- -moz- -o- -ms- ".split(" "),
B="Webkit Moz O ms".split(" "),C="webkit moz o ms".split(" "),a={},D={},n={},v=[],w=v.slice,t,m=function(d,b,a,o){var f,h,c=e.createElement("div"),i=e.body,g=i||e.createElement("body");if(parseInt(a,10))for(;a--;)f=e.createElement("div"),f.id=o?o[a]:"modernizr"+(a+1),c.appendChild(f);a=['&#173;<style id="smodernizr">',d,"</style>"].join("");c.id="modernizr";(i?c:g).innerHTML+=a;g.appendChild(c);if(!i)g.style.background="",g.style.overflow="hidden",h=j.style.overflow,j.style.overflow="hidden",j.appendChild(g);
d=b(c,d);i?c.parentNode.removeChild(c):(g.parentNode.removeChild(g),j.style.overflow=h);return!!d},F=function(){var d={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(b,a){var a=a||e.createElement(d[b]||"div"),b="on"+b,f=b in a;f||(a.setAttribute||(a=e.createElement("div")),a.setAttribute&&a.removeAttribute&&(a.setAttribute(b,""),f=k(a[b],"function"),k(a[b],"undefined")||(a[b]=l),a.removeAttribute(b)));return f}}(),x={}.hasOwnProperty,y;
y=!k(x,"undefined")&&!k(x.call,"undefined")?function(d,a){return x.call(d,a)}:function(d,a){return a in d&&k(d.constructor.prototype[a],"undefined")};if(!Function.prototype.bind)Function.prototype.bind=function(d){var a=this;if("function"!=typeof a)throw new TypeError;var f=w.call(arguments,1),e=function(){if(this instanceof e){var c=function(){};c.prototype=a.prototype;var c=new c,g=a.apply(c,f.concat(w.call(arguments)));return Object(g)===g?g:c}return a.apply(d,f.concat(w.call(arguments)))};return e};
a.flexbox=function(){return c("flexWrap")};a.flexboxlegacy=function(){return c("boxDirection")};a.canvas=function(){var a=e.createElement("canvas");return!(!a.getContext||!a.getContext("2d"))};a.canvastext=function(){return!(!f.canvas||!k(e.createElement("canvas").getContext("2d").fillText,"function"))};a.webgl=function(){return!!h.WebGLRenderingContext};a.touch=function(){var a;"ontouchstart"in h||h.DocumentTouch&&e instanceof DocumentTouch?a=!0:m(["@media (",p.join("touch-enabled),("),"modernizr){#modernizr{top:9px;position:absolute}}"].join(""),
function(b){a=9===b.offsetTop});return a};a.geolocation=function(){return"geolocation"in navigator};a.postmessage=function(){return!!h.postMessage};a.websqldatabase=function(){return!!h.openDatabase};a.indexedDB=function(){return!!c("indexedDB",h)};a.hashchange=function(){return F("hashchange",h)&&(e.documentMode===l||7<e.documentMode)};a.history=function(){return!(!h.history||!history.pushState)};a.draganddrop=function(){var a=e.createElement("div");return"draggable"in a||"ondragstart"in a&&"ondrop"in
a};a.websockets=function(){return"WebSocket"in h||"MozWebSocket"in h};a.rgba=function(){g.cssText="background-color:rgba(150,255,150,.5)";return!!~(""+g.backgroundColor).indexOf("rgba")};a.hsla=function(){g.cssText="background-color:hsla(120,40%,100%,.5)";return!!~(""+g.backgroundColor).indexOf("rgba")||!!~(""+g.backgroundColor).indexOf("hsla")};a.multiplebgs=function(){g.cssText="background:url(https://),url(https://),red url(https://)";return/(url\s*\(.*?){3}/.test(g.background)};a.backgroundsize=
function(){return c("backgroundSize")};a.borderimage=function(){return c("borderImage")};a.borderradius=function(){return c("borderRadius")};a.boxshadow=function(){return c("boxShadow")};a.textshadow=function(){return""===e.createElement("div").style.textShadow};a.opacity=function(){var a=p.join("opacity:.55;")+"";g.cssText=a;return/^0.55$/.test(g.opacity)};a.cssanimations=function(){return c("animationName")};a.csscolumns=function(){return c("columnCount")};a.cssgradients=function(){var a=("background-image:"+
"-webkit- ".split(" ").join("gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:")+p.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,-17);g.cssText=a;return!!~(""+g.backgroundImage).indexOf("gradient")};a.cssreflections=function(){return c("boxReflect")};a.csstransforms=function(){return!!c("transform")};a.csstransforms3d=function(){var a=!!c("perspective");a&&"webkitPerspective"in j.style&&m("@media (transform-3d),(-webkit-transform-3d){#modernizr{left:9px;position:absolute;height:3px;}}",
function(b){a=9===b.offsetLeft&&3===b.offsetHeight});return a};a.csstransitions=function(){return c("transition")};a.fontface=function(){var a;m('@font-face {font-family:"font";src:url("https://")}',function(b,f){var c=e.getElementById("smodernizr"),c=(c=c.sheet||c.styleSheet)?c.cssRules&&c.cssRules[0]?c.cssRules[0].cssText:c.cssText||"":"";a=/src/i.test(c)&&0===c.indexOf(f.split(" ")[0])});return a};a.generatedcontent=function(){var a;m(['#modernizr{font:0/0 a}#modernizr:after{content:"',u,'";visibility:hidden;font:3px/1 a}'].join(""),
function(b){a=3<=b.offsetHeight});return a};a.video=function(){var a=e.createElement("video"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,""),b.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,""),b.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,"")}catch(c){}return b};a.audio=function(){var a=e.createElement("audio"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,
""),b.mp3=a.canPlayType("audio/mpeg;").replace(/^no$/,""),b.wav=a.canPlayType('audio/wav; codecs="1"').replace(/^no$/,""),b.m4a=(a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;")).replace(/^no$/,"")}catch(c){}return b};a.localstorage=function(){try{return localStorage.setItem("modernizr","modernizr"),localStorage.removeItem("modernizr"),!0}catch(a){return!1}};a.sessionstorage=function(){try{return sessionStorage.setItem("modernizr","modernizr"),sessionStorage.removeItem("modernizr"),!0}catch(a){return!1}};
a.webworkers=function(){return!!h.Worker};a.applicationcache=function(){return!!h.applicationCache};a.svg=function(){return!!e.createElementNS&&!!e.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect};a.inlinesvg=function(){var a=e.createElement("div");a.innerHTML="<svg/>";return"http://www.w3.org/2000/svg"==(a.firstChild&&a.firstChild.namespaceURI)};a.smil=function(){return!!e.createElementNS&&/SVGAnimate/.test(E.call(e.createElementNS("http://www.w3.org/2000/svg","animate")))};a.svgclippaths=
function(){return!!e.createElementNS&&/SVGClipPath/.test(E.call(e.createElementNS("http://www.w3.org/2000/svg","clipPath")))};for(var z in a)y(a,z)&&(t=z.toLowerCase(),f[t]=a[z](),v.push((f[t]?"":"no-")+t));f.input||G();f.addTest=function(a,b){if("object"==typeof a)for(var c in a)y(a,c)&&f.addTest(c,a[c]);else{a=a.toLowerCase();if(f[a]!==l)return f;b="function"==typeof b?b():b;j.className+=" "+(b?"":"no-")+a;f[a]=b}return f};g.cssText="";a=i=null;(function(a,b){function c(){var a=r.elements;return"string"==
typeof a?a.split(" "):a}function f(a){var b=p[a[m]];b||(b={},n++,a[m]=n,p[n]=b);return b}function e(a,c,d){c||(c=b);if(q)return c.createElement(a);d||(d=f(c));c=d.cache[a]?d.cache[a].cloneNode():k.test(a)?(d.cache[a]=d.createElem(a)).cloneNode():d.createElem(a);return c.canHaveChildren&&!j.test(a)?d.frag.appendChild(c):c}function g(a,b){if(!b.cache)b.cache={},b.createElem=a.createElement,b.createFrag=a.createDocumentFragment,b.frag=b.createFrag();a.createElement=function(c){return!r.shivMethods?b.createElem(c):
e(c,a,b)};a.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+c().join().replace(/\w+/g,function(a){b.createElem(a);b.frag.createElement(a);return'c("'+a+'")'})+");return n}")(r,b.frag)}function i(a){a||(a=b);var c=f(a);if(r.shivCSS&&!l&&!c.hasCSS){var d,e=a;d=e.createElement("p");e=e.getElementsByTagName("head")[0]||e.documentElement;d.innerHTML="x<style>article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}mark{background:#FF0;color:#000}</style>";
d=e.insertBefore(d.lastChild,e.firstChild);c.hasCSS=!!d}q||g(a,c);return a}var h=a.html5||{},j=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,k=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,l,m="_html5shiv",n=0,p={},q;(function(){try{var a=b.createElement("a");a.innerHTML="<xyz></xyz>";l="hidden"in a;var c;if(!(c=1==a.childNodes.length)){b.createElement("a");var d=b.createDocumentFragment();c="undefined"==typeof d.cloneNode||
"undefined"==typeof d.createDocumentFragment||"undefined"==typeof d.createElement}q=c}catch(e){q=l=!0}})();var r={elements:h.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",shivCSS:!1!==h.shivCSS,supportsUnknownElements:q,shivMethods:!1!==h.shivMethods,type:"default",shivDocument:i,createElement:e,createDocumentFragment:function(a,d){a||(a=b);if(q)return a.createDocumentFragment();
for(var d=d||f(a),e=d.frag.cloneNode(),g=0,h=c(),i=h.length;g<i;g++)e.createElement(h[g]);return e}};a.html5=r;i(b)})(this,e);f._version="2.6.2";f._prefixes=p;f._domPrefixes=C;f._cssomPrefixes=B;f.mq=function(a){var b=h.matchMedia||h.msMatchMedia;if(b)return b(a).matches;var c;m("@media "+a+" { #modernizr { position: absolute; } }",function(a){c="absolute"==(h.getComputedStyle?getComputedStyle(a,null):a.currentStyle).position});return c};f.hasEvent=F;f.testProp=function(a){return A([a])};f.testAllProps=
c;f.testStyles=m;f.prefixed=function(a,b,e){return b?c(a,b,e):c(a,"pfx")};j.className=j.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(" js "+v.join(" "));return f}(this,this.document);
